container:
  image: google/dart-runtime:latest

app_task:
  env:
    matrix:
      - CIRRUS_WORKING_DIR: app
      - CIRRUS_WORKING_DIR: app_dart
  pub_script: pub get
  analyze_script: dartanalyzer --options analysis_options.yaml .
  build_script: pub run build_runner build
  test_script: pub run test
