container:
  image: google/dart-runtime:latest

app_task:
  env:
    matrix:
      - CWD: app
      - CWD: app_dart
  pub_script: cd $CWD && pub get
  analyze_script: cd $CWD && dartanalyzer --options analysis_options.yaml .
  build_script: cd $CWD && pub run build_runner build
  test_script: cd $CWD && pub run test
