container:
  image: google/dart-runtime:dev

task:
  name: $CWD
  env:
    matrix:
      - CWD: app
      - CWD: app_dart
      - CWD: agent
  pub_script: cd $CWD && pub get
  build_analyze_script: ./build_and_analyze.sh $CWD
  test_script: cd $CWD && pub run test -r expanded
