container:
  image: google/dart-runtime:latest

app_task:
  env:
    matrix:
      # TODO(dnfield): Enable this.
      # - CWD: app
      - CWD: app_dart
  pub_script: cd $CWD && pub get
  build_script: cd $CWD && pub run build_runner build
  analyze_script: ./analyze.sh $CWD
  test_script: cd $CWD && pub run test
